wandb_version: 1

filter_1:
  desc: null
  value: 10
kernel_1:
  desc: null
  value: 3
activation_1:
  desc: null
  value: relu
strides_1:
  desc: null
  value: 1
MaxPoolSize_1:
  desc: null
  value: 2
filter_2:
  desc: null
  value: 10
kernel_2:
  desc: null
  value: 3
activation_2:
  desc: null
  value: relu
strides_2:
  desc: null
  value: 1
filter_3:
  desc: null
  value: 10
kernel_3:
  desc: null
  value: 3
activation_3:
  desc: null
  value: relu
strides_3:
  desc: null
  value: 1
filter_4:
  desc: null
  value: 10
kernel_4:
  desc: null
  value: 3
activation_4:
  desc: null
  value: relu
strides_4:
  desc: null
  value: 1
MaxPoolSize_2:
  desc: null
  value: 2
padding:
  desc: null
  value: valid
dense_1:
  desc: null
  value: 1
activation_output:
  desc: null
  value: sigmoid
optimizer:
  desc: null
  value: Adam
loss:
  desc: null
  value: binary_crossentropy
metric:
  desc: null
  value: accuracy
epoch:
  desc: null
  value: 5
batch_size:
  desc: null
  value: 32
_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.17.0
    framework: keras
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1716128588
    t:
      1:
      - 2
      - 3
      - 12
      - 55
      2:
      - 2
      - 3
      - 12
      - 55
      3:
      - 2
      - 7
      - 16
      - 23
      - 38
      - 39
      4: 3.10.12
      5: 0.17.0
      8:
      - 1
      - 5
      - 12
      13: linux-x86_64
    m:
    - 1: batch/batch_step
      6:
      - 3
    - 1: batch/loss
      5: 1
      6:
      - 1
    - 1: batch/accuracy
      5: 1
      6:
      - 1
    - 1: batch/learning_rate
      5: 1
      6:
      - 1
